module.exports = {
  ExternalId: 'string',
  String: 'string',
  WikibaseItem: 'entity',
  Time: 'time',
  Monolingualtext: 'monolingualtext',
  Quantity: 'quantity',
  GlobeCoordinate: 'globecoordinate',
  WikibaseProperty: 'entity',
  Url: 'string',
  CommonsMedia: 'string',
  'external-id': 'string',
  string: 'string',
  'wikibase-item': 'entity',
  time: 'time',
  monolingualtext: 'monolingualtext',
  quantity: 'quantity',
  'globe-coordinate': 'globecoordinate',
  'wikibase-property': 'entity',
  url: 'string',
  'commons-media': 'string'
}
